dist: xenial
sudo: false
language: cpp
compiler: gcc
addons:
  apt:
    packages:
    - libgtest-dev
    - librtmp-dev
script: make -C ui/linux && make -C ui/linux/tests && cd ui/linux/tests && ./test-all && cd ../../../bvt && cp -R ../ui/linux/peercast-yt . && ruby test-all.rb
